name: "Teach"
about: "Create a new task, feature, or refactor request"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 **Context**

        As a:

        I want to:

        So that:

        ## 🎯 **Goal**

        As a:

        I want to:

        So that:

        ## 📝 **Scenario**

        Given:

        When:

        Then:

        ## 📌 **Acceptance Criteria**

        ## 🏷 **Labels**

        ## ⏳ **Priority & Estimated Time**
        - **Priority:**
        - **Estimated Time:**

        ## 📋 **Teach Checklist**
